### ISSUE TITLE
Is there anyway to decrease feature usage?

### ISSUE THREAD

**Issue by duongtdvn** [renoki-co/cashier-register#15]
Hi, just found out this awesome package but i was wondering if it can decrease the feature usage. For example I have a plan which limit user to create up to 5 photos. I can count them up as the docs say by use `$subscription->recordFeatureUsage(1)` everytime user create a new photo. But if they remove photo should we release the slot so they can use up again?

**Comment by rennokki** [comment]
`->reduceFeatureUsage()`: https://github.com/renoki-co/cashier-register/blob/master/src/Concerns/HasQuotas.php#L58
