### ISSUE TITLE
Replacing models is not very flexible, let's discuss improvements

### ISSUE THREAD

**Issue by Djuki** [renoki-co/cashier-register#18]
I have a situation that all my models need to extend
```Jenssegers\Mongodb\Eloquent\Model```
because I am using MongoDB.

I set the configuration file to use my models:
```
    'models' => [

        'usage' => \App\Entities\App\Subscription\Usage::class,

    ],
```

The issue is my model can't extend `RenokiCo\CashierRegister\Models`, and for that reason, I can exceptions like this one when resetting quotas.

```
TypeError: Argument 1 passed to App\Entities\App\Subscription\Subscription::RenokiCo\CashierRegister\Concerns\{closure}() must be an instance of RenokiCo\CashierRegister\Models\Usage, instance of App\Entities\App\Subscription\Usage given, called in /var/www/saas-starter/vendor/laravel/framework/src/Illuminate/Collections/Traits/EnumeratesValues.php on line 230
```

Reason Is the package has a type check and expect models to extend `RenokiCo\CashierRegister\Models`. As I explained in some cases we do not want to use Eloquent, so I want to propose a change that instead of type check for models, we add Contracts (interfaces), and type check interfaces, which would make it more flexible.

I would like to hear other opinions first, and I can propose PR when we make a plan.

cc @rennokki

**Comment by rennokki** [comment]
Feel free to add here if something else's broken in MongoDB.
