### ISSUE TITLE
Update to new cashier

### ISSUE THREAD

**Issue by kiwina** [renoki-co/cashier-register#20]
Hi, just came across this package, when i'm installing it apart from failing in dependencies cashier now has useSubscriptionModel witch makes BillableWithXXX redundant and they changed to polymorfic relations. Be nice to have it in a future update

**Comment by rennokki** [comment]
@kiwina I can't see any relevant info on Cashier Stripe that they use Polymorphic Relationships. The BillableWithStripe will be removed and instead be used with the new feature.

Why are the dependencies failing? Can you give more insight?
