### ISSUE TITLE
Multiplan Subscriptions fail to identify plan

### ISSUE THREAD

**Issue by nickfls** [renoki-co/cashier-register#40]
Laravel: 8.44
Cashier Register: 5.02
Cashier / Stripe: 12.14

When laravel cashier registers [Multiplan Subscriptions](https://laravel.com/docs/8.x/billing#multiplan-subscriptions) it wipes stripe_id from `subscriptions` table [PR#1048](https://github.com/laravel/cashier-stripe/pull/1048/files)

CashierRegister relies on that value to identify registered Saas plan and as a result, `recordFeatureUsage` fails because getPlan() returns `null`

**Comment by nickfls** [comment]
Maybe:

1. Take the oldest subscription from `subscription_items`?
2. Allow to register a Closure to defer to user to identify the  appropriate plan from `subscription_items`?
3. Both?

**Comment by rennokki** [comment]
I think it would have been worth noting the fact that multi-plan subscriptions are not supported yet.
