### ISSUE TITLE
Cashier uses stripe_product rather than stripe_plan

### ISSUE THREAD

**Issue by natecorkish** [renoki-co/cashier-register#42]
https://github.com/laravel/cashier-stripe/blob/17a514225a524f50466a6c270aab4566646bf1c4/database/migrations/2019_05_03_000003_create_subscription_items_table.php#L20

https://github.com/renoki-co/cashier-register/blob/1a50db5b78f4fdb2ec8fa23320d3a31bfaf8c0c3/src/Models/Stripe/Subscription.php#L21

https://github.com/renoki-co/cashier-register/blob/1d654b1d016463019de34ef5fd8d06eebf5b7fe3/src/Concerns/HasPlans.php#L26

Could we get a PR to fix this, because currently, it's returning the free plan even if the user has another plan due to a mixup of table names?

**Comment by rennokki** [comment]
This package supports Cashier up to 12.x included: https://rennokki.gitbook.io/cashier-register/getting-started/installation#cashier-for-stripe
Will upgrade Cashier Register's support to Stripe 13.x 😁

**Comment by rennokki** [comment]
Tagged 6.0

In case you come from Cashier Stripe 12.x, check their upgrade notes: https://github.com/laravel/cashier-stripe/blob/13.x/UPGRADE.md
