### ISSUE TITLE
paddle support

### ISSUE THREAD

**Issue by arunbabucode** [renoki-co/cashier-register#9]
Thanks for the package, can you merge the paddle branch?

**Comment by rennokki** [comment]
Paddle is still under construction 👀 gonna fix it and merge it this week or so.

**Comment by arunbabucode** [comment]
Awesome, thanks

**Comment by rennokki** [comment]
@arunbabucode Please check the `3.0.0` tag for instructions on updating: https://github.com/renoki-co/cashier-register/releases/tag/3.0.0

**Comment by arunbabucode** [comment]
@rennokki Perfect, thanks. On the paddle version for `CashierRegisterServiceProvider.php`,  on line 6, it seems its hardcoded for the cashier stripe. Maybe it's better you define the provider (stripe/cashier) to use in the config and then importing the class automatically based on the configured provider?

**Comment by rennokki** [comment]
Nice catch. I think I will move this in the stub

**Comment by rennokki** [comment]
Wait, no, I'm a lil dumb haha, it seems like it shouldn't sit there at all. The package provides only one table to run with.

**Comment by rennokki** [comment]
Tagged 3.0.1. Give it about 3-4 minutes to propagate to Packagist.

https://github.com/renoki-co/cashier-register/releases/tag/3.0.1

**Comment by arunbabucode** [comment]
So far so good. Closing.
